export const FETCH_PICTOGRAMS_PENDING = 'FETCH_PICTOGRAMS_PENDING';
export const FETCH_PICTOGRAMS_ERROR = 'FETCH_PICTOGRAMS_ERROR';
export const FETCH_PICTOGRAMS_SUCCESS = 'FETCH_PICTOGRAMS_SUCCESS';

export const ADD_PICTOGRAM_SUCCESS = 'ADD_PICTOGRAM_SUCCESS';
export const ADD_PICTOGRAM_ERROR = 'ADD_PICTOGRAM_ERROR';
export const UPDATE_PICTOGRAM_SUCCESS = 'UPDATE_PICTOGRAM_SUCCESS';
export const UPDATE_PICTOGRAM_ERROR = 'UPDATE_PICTOGRAM_ERROR';
export const DELETE_PICTOGRAM_SUCCESS = 'DELETE_PICTOGRAM_SUCCESS';
export const DELETE_PICTOGRAM_ERROR = 'DELETE_PICTOGRAM_ERROR';

export const FILTER_PICTOGRAMS_BY_CATEGORY = 'FILTER_PICTOGRAMS_BY_CATEGORY';