export const FETCH_ROUTINES_PENDING = 'FETCH_ROUTINES_PENDING';
export const FETCH_ROUTINES_SUCCESS = 'FETCH_ROUTINES_SUCCESS';
export const FETCH_ROUTINES_ERROR = 'FETCH_ROUTINES_ERROR';

export const ADD_ROUTINE_SUCCESS = 'ADD_ROUTINE_SUCCESS';
export const ADD_ROUTINE_ERROR = 'ADD_ROUTINE_ERROR';
export const UPDATE_ROUTINE_SUCCESS = 'UPDATE_ROUTINE_SUCCESS';
export const UPDATE_ROUTINE_ERROR = 'UPDATE_ROUTINE_ERROR';
export const DELETE_ROUTINE_SUCCESS = 'DELETE_ROUTINE_SUCCESS';
export const DELETE_ROUTINE_ERROR = 'DELETE_ROUTINE_ERROR';