export const FETCH_ROUTINES_PENDING = 'FETCH_ROUTINES_PENDING';
export const FETCH_ROUTINES_SUCCESS = 'FETCH_ROUTINES_SUCCESS';
export const FETCH_ROUTINES_ERROR = 'FETCH_ROUTINES_ERROR';

export const ADD_ROUTINE_SUCCESS = 'ADD_ROUTINE_SUCCESS';
export const ADD_ROUTINE_EROOR = 'ADD_ROUTINE_EROOR';